INSERT INTO user (username, password, role) VALUES ('admin', 'admin', 'ADMIN');

INSERT INTO language (lang) VALUES ('en');

INSERT INTO rebus_image_puzzle (image_word, word_lang, image_name, image_word_type) VALUES ('0', 1, '0.png', 1);
INSERT INTO rebus_image_puzzle (image_word, word_lang, image_name, image_word_type) VALUES ('1', 1, '1.png', 1);
INSERT INTO rebus_image_puzzle (image_word, word_lang, image_name, image_word_type) VALUES ('2', 1, '2.png', 1);
INSERT INTO rebus_image_puzzle (image_word, word_lang, image_name, image_word_type) VALUES ('3', 1, '3.png', 1);
INSERT INTO rebus_image_puzzle (image_word, word_lang, image_name, image_word_type) VALUES ('4', 1, '4.png', 1);
INSERT INTO rebus_image_puzzle (image_word, word_lang, image_name, image_word_type) VALUES ('5', 1, '5.png', 1);
INSERT INTO rebus_image_puzzle (image_word, word_lang, image_name, image_word_type) VALUES ('6', 1, '6.png', 1);
INSERT INTO rebus_image_puzzle (image_word, word_lang, image_name, image_word_type) VALUES ('7', 1, '7.png', 1);
INSERT INTO rebus_image_puzzle (image_word, word_lang, image_name, image_word_type) VALUES ('8', 1, '8.png', 1);
INSERT INTO rebus_image_puzzle (image_word, word_lang, image_name, image_word_type) VALUES ('9', 1, '9.png', 1)

INSERT INTO rebus_image_puzzle (image_word, word_lang, image_name, image_word_type) VALUES ('a', 1, 'a_en.png', 1);
INSERT INTO rebus_image_puzzle (image_word, word_lang, image_name, image_word_type) VALUES ('b', 1, 'b_en.png', 1);
INSERT INTO rebus_image_puzzle (image_word, word_lang, image_name, image_word_type) VALUES ('c', 1, 'c_en.png', 1);
INSERT INTO rebus_image_puzzle (image_word, word_lang, image_name, image_word_type) VALUES ('d', 1, 'd_en.png', 1);
INSERT INTO rebus_image_puzzle (image_word, word_lang, image_name, image_word_type) VALUES ('e', 1, 'e_en.png', 1);
INSERT INTO rebus_image_puzzle (image_word, word_lang, image_name, image_word_type) VALUES ('f', 1, 'f_en.png', 1);
INSERT INTO rebus_image_puzzle (image_word, word_lang, image_name, image_word_type) VALUES ('g', 1, 'g_en.png', 1);
INSERT INTO rebus_image_puzzle (image_word, word_lang, image_name, image_word_type) VALUES ('h', 1, 'h_en.png', 1);
INSERT INTO rebus_image_puzzle (image_word, word_lang, image_name, image_word_type) VALUES ('i', 1, 'i_en.png', 1);
INSERT INTO rebus_image_puzzle (image_word, word_lang, image_name, image_word_type) VALUES ('j', 1, 'j_en.png', 1);
INSERT INTO rebus_image_puzzle (image_word, word_lang, image_name, image_word_type) VALUES ('k', 1, 'k_en.png', 1);
INSERT INTO rebus_image_puzzle (image_word, word_lang, image_name, image_word_type) VALUES ('l', 1, 'l_en.png', 1);
INSERT INTO rebus_image_puzzle (image_word, word_lang, image_name, image_word_type) VALUES ('m', 1, 'm_en.png', 1);
INSERT INTO rebus_image_puzzle (image_word, word_lang, image_name, image_word_type) VALUES ('n', 1, 'n_en.png', 1);
INSERT INTO rebus_image_puzzle (image_word, word_lang, image_name, image_word_type) VALUES ('o', 1, 'o_en.png', 1);
INSERT INTO rebus_image_puzzle (image_word, word_lang, image_name, image_word_type) VALUES ('p', 1, 'p_en.png', 1);
INSERT INTO rebus_image_puzzle (image_word, word_lang, image_name, image_word_type) VALUES ('q', 1, 'q_en.png', 1);
INSERT INTO rebus_image_puzzle (image_word, word_lang, image_name, image_word_type) VALUES ('r', 1, 'r_en.png', 1);
INSERT INTO rebus_image_puzzle (image_word, word_lang, image_name, image_word_type) VALUES ('s', 1, 's_en.png', 1);
INSERT INTO rebus_image_puzzle (image_word, word_lang, image_name, image_word_type) VALUES ('t', 1, 't_en.png', 1);
INSERT INTO rebus_image_puzzle (image_word, word_lang, image_name, image_word_type) VALUES ('u', 1, 'u_en.png', 1);
INSERT INTO rebus_image_puzzle (image_word, word_lang, image_name, image_word_type) VALUES ('v', 1, 'v_en.png', 1);
INSERT INTO rebus_image_puzzle (image_word, word_lang, image_name, image_word_type) VALUES ('w', 1, 'w_en.png', 1);
INSERT INTO rebus_image_puzzle (image_word, word_lang, image_name, image_word_type) VALUES ('x', 1, 'x_en.png', 1);
INSERT INTO rebus_image_puzzle (image_word, word_lang, image_name, image_word_type) VALUES ('y', 1, 'y_en.png', 1);
INSERT INTO rebus_image_puzzle (image_word, word_lang, image_name, image_word_type) VALUES ('z', 1, 'z_en.png', 1);

INSERT INTO rebus_image_puzzle (image_word, word_lang, image_name, image_word_type) VALUES ('crossed_a', 1, 'crossed_a_en.png', 1);
INSERT INTO rebus_image_puzzle (image_word, word_lang, image_name, image_word_type) VALUES ('crossed_b', 1, 'crossed_b_en.png', 1);
INSERT INTO rebus_image_puzzle (image_word, word_lang, image_name, image_word_type) VALUES ('crossed_c', 1, 'crossed_c_en.png', 1);
INSERT INTO rebus_image_puzzle (image_word, word_lang, image_name, image_word_type) VALUES ('crossed_d', 1, 'crossed_d_en.png', 1);
INSERT INTO rebus_image_puzzle (image_word, word_lang, image_name, image_word_type) VALUES ('crossed_e', 1, 'crossed_e_en.png', 1);
INSERT INTO rebus_image_puzzle (image_word, word_lang, image_name, image_word_type) VALUES ('crossed_f', 1, 'crossed_f_en.png', 1);
INSERT INTO rebus_image_puzzle (image_word, word_lang, image_name, image_word_type) VALUES ('crossed_g', 1, 'crossed_g_en.png', 1);
INSERT INTO rebus_image_puzzle (image_word, word_lang, image_name, image_word_type) VALUES ('crossed_h', 1, 'crossed_h_en.png', 1);
INSERT INTO rebus_image_puzzle (image_word, word_lang, image_name, image_word_type) VALUES ('crossed_i', 1, 'crossed_i_en.png', 1);
INSERT INTO rebus_image_puzzle (image_word, word_lang, image_name, image_word_type) VALUES ('crossed_j', 1, 'crossed_j_en.png', 1);
INSERT INTO rebus_image_puzzle (image_word, word_lang, image_name, image_word_type) VALUES ('crossed_k', 1, 'crossed_k_en.png', 1);
INSERT INTO rebus_image_puzzle (image_word, word_lang, image_name, image_word_type) VALUES ('crossed_l', 1, 'crossed_l_en.png', 1);
INSERT INTO rebus_image_puzzle (image_word, word_lang, image_name, image_word_type) VALUES ('crossed_m', 1, 'crossed_m_en.png', 1);
INSERT INTO rebus_image_puzzle (image_word, word_lang, image_name, image_word_type) VALUES ('crossed_n', 1, 'crossed_n_en.png', 1);
INSERT INTO rebus_image_puzzle (image_word, word_lang, image_name, image_word_type) VALUES ('crossed_o', 1, 'crossed_o_en.png', 1);
INSERT INTO rebus_image_puzzle (image_word, word_lang, image_name, image_word_type) VALUES ('crossed_p', 1, 'crossed_p_en.png', 1);
INSERT INTO rebus_image_puzzle (image_word, word_lang, image_name, image_word_type) VALUES ('crossed_q', 1, 'crossed_q_en.png', 1);
INSERT INTO rebus_image_puzzle (image_word, word_lang, image_name, image_word_type) VALUES ('crossed_r', 1, 'crossed_r_en.png', 1);
INSERT INTO rebus_image_puzzle (image_word, word_lang, image_name, image_word_type) VALUES ('crossed_s', 1, 'crossed_s_en.png', 1);
INSERT INTO rebus_image_puzzle (image_word, word_lang, image_name, image_word_type) VALUES ('crossed_t', 1, 'crossed_t_en.png', 1);
INSERT INTO rebus_image_puzzle (image_word, word_lang, image_name, image_word_type) VALUES ('crossed_u', 1, 'crossed_u_en.png', 1);
INSERT INTO rebus_image_puzzle (image_word, word_lang, image_name, image_word_type) VALUES ('crossed_v', 1, 'crossed_v_en.png', 1);
INSERT INTO rebus_image_puzzle (image_word, word_lang, image_name, image_word_type) VALUES ('crossed_w', 1, 'crossed_w_en.png', 1);
INSERT INTO rebus_image_puzzle (image_word, word_lang, image_name, image_word_type) VALUES ('crossed_x', 1, 'crossed_x_en.png', 1);
INSERT INTO rebus_image_puzzle (image_word, word_lang, image_name, image_word_type) VALUES ('crossed_y', 1, 'crossed_y_en.png', 1);
INSERT INTO rebus_image_puzzle (image_word, word_lang, image_name, image_word_type) VALUES ('crossed_z', 1, 'crossed_z_en.png', 1);

INSERT INTO rebus_image_puzzle (image_word, word_lang, image_name, image_word_type) VALUES ('front_comma', 1, 'front_comma.png', 1);
INSERT INTO rebus_image_puzzle (image_word, word_lang, image_name, image_word_type) VALUES ('back_comma', 1, 'back_comma.png', 1);
INSERT INTO rebus_image_puzzle (image_word, word_lang, image_name, image_word_type) VALUES ('equals_sign', 1, 'equals_sign.png', 1);

INSERT INTO rebus_image_puzzle (image_word, word_lang, image_name, image_word_type) VALUES ('axe', 1, 'axe.png', 0);
INSERT INTO rebus_image_puzzle (image_word, word_lang, image_name, image_word_type) VALUES ('bag', 1, 'bag.png', 0);
INSERT INTO rebus_image_puzzle (image_word, word_lang, image_name, image_word_type) VALUES ('bat', 1, 'bat.png', 0);
INSERT INTO rebus_image_puzzle (image_word, word_lang, image_name, image_word_type) VALUES ('bath', 1, 'bath.png', 0);
INSERT INTO rebus_image_puzzle (image_word, word_lang, image_name, image_word_type) VALUES ('bed', 1, 'bed.png', 0);
INSERT INTO rebus_image_puzzle (image_word, word_lang, image_name, image_word_type) VALUES ('bee', 1, 'bee.png', 0);
INSERT INTO rebus_image_puzzle (image_word, word_lang, image_name, image_word_type) VALUES ('bike', 1, 'bike.png', 0);
INSERT INTO rebus_image_puzzle (image_word, word_lang, image_name, image_word_type) VALUES ('bird', 1, 'note.png', 0);
INSERT INTO rebus_image_puzzle (image_word, word_lang, image_name, image_word_type) VALUES ('bone', 1, 'bone.png', 0);
INSERT INTO rebus_image_puzzle (image_word, word_lang, image_name, image_word_type) VALUES ('boot', 1, 'boot.png', 0);
INSERT INTO rebus_image_puzzle (image_word, word_lang, image_name, image_word_type) VALUES ('bottle', 1, 'bottle.png', 0);
INSERT INTO rebus_image_puzzle (image_word, word_lang, image_name, image_word_type) VALUES ('bug', 1, 'bug.png', 0);
INSERT INTO rebus_image_puzzle (image_word, word_lang, image_name, image_word_type) VALUES ('bus', 1, 'bus.png', 0);
INSERT INTO rebus_image_puzzle (image_word, word_lang, image_name, image_word_type) VALUES ('cake', 1, 'cake.png', 0);
INSERT INTO rebus_image_puzzle (image_word, word_lang, image_name, image_word_type) VALUES ('candle', 1, 'candle.png', 0);
INSERT INTO rebus_image_puzzle (image_word, word_lang, image_name, image_word_type) VALUES ('car', 1, 'car.png', 0);
INSERT INTO rebus_image_puzzle (image_word, word_lang, image_name, image_word_type) VALUES ('cat', 1, 'cat.png', 0);
INSERT INTO rebus_image_puzzle (image_word, word_lang, image_name, image_word_type) VALUES ('cheese', 1, 'cheese.png', 0);
INSERT INTO rebus_image_puzzle (image_word, word_lang, image_name, image_word_type) VALUES ('computer', 1, 'computer.png', 0);
INSERT INTO rebus_image_puzzle (image_word, word_lang, image_name, image_word_type) VALUES ('crab', 1, 'crab.png', 0);
INSERT INTO rebus_image_puzzle (image_word, word_lang, image_name, image_word_type) VALUES ('cup', 1, 'cup.png', 0);
INSERT INTO rebus_image_puzzle (image_word, word_lang, image_name, image_word_type) VALUES ('dog', 1, 'dog.png', 0);
INSERT INTO rebus_image_puzzle (image_word, word_lang, image_name, image_word_type) VALUES ('door', 1, 'door.png', 0);
INSERT INTO rebus_image_puzzle (image_word, word_lang, image_name, image_word_type) VALUES ('egg', 1, 'egg.png', 0);
INSERT INTO rebus_image_puzzle (image_word, word_lang, image_name, image_word_type) VALUES ('eye', 1, 'eye.png', 0);
INSERT INTO rebus_image_puzzle (image_word, word_lang, image_name, image_word_type) VALUES ('fire', 1, 'fire.png', 0);
INSERT INTO rebus_image_puzzle (image_word, word_lang, image_name, image_word_type) VALUES ('fish', 1, 'fish.png', 0);
INSERT INTO rebus_image_puzzle (image_word, word_lang, image_name, image_word_type) VALUES ('flower', 1, 'flower.png', 0);
INSERT INTO rebus_image_puzzle (image_word, word_lang, image_name, image_word_type) VALUES ('hat', 1, 'hat.png', 0);
INSERT INTO rebus_image_puzzle (image_word, word_lang, image_name, image_word_type) VALUES ('heart', 1, 'heart.png', 0);
INSERT INTO rebus_image_puzzle (image_word, word_lang, image_name, image_word_type) VALUES ('horse', 1, 'horse.png', 0);
INSERT INTO rebus_image_puzzle (image_word, word_lang, image_name, image_word_type) VALUES ('lion', 1, 'lion.png', 0);
INSERT INTO rebus_image_puzzle (image_word, word_lang, image_name, image_word_type) VALUES ('map', 1, 'map.png', 0);
INSERT INTO rebus_image_puzzle (image_word, word_lang, image_name, image_word_type) VALUES ('money', 1, 'money.png', 0);
INSERT INTO rebus_image_puzzle (image_word, word_lang, image_name, image_word_type) VALUES ('moon', 1, 'moon.png', 0);
INSERT INTO rebus_image_puzzle (image_word, word_lang, image_name, image_word_type) VALUES ('mouth', 1, 'mouth.png', 0);
INSERT INTO rebus_image_puzzle (image_word, word_lang, image_name, image_word_type) VALUES ('noodles', 1, 'noodles.png', 0);
INSERT INTO rebus_image_puzzle (image_word, word_lang, image_name, image_word_type) VALUES ('note', 1, 'note.png', 0);
INSERT INTO rebus_image_puzzle (image_word, word_lang, image_name, image_word_type) VALUES ('phone', 1, 'phone.png', 0);
INSERT INTO rebus_image_puzzle (image_word, word_lang, image_name, image_word_type) VALUES ('pig', 1, 'pig.png', 0);
INSERT INTO rebus_image_puzzle (image_word, word_lang, image_name, image_word_type) VALUES ('plane', 1, 'plane.png', 0);
INSERT INTO rebus_image_puzzle (image_word, word_lang, image_name, image_word_type) VALUES ('rain', 1, 'rain.png', 0);
INSERT INTO rebus_image_puzzle (image_word, word_lang, image_name, image_word_type) VALUES ('shark', 1, 'shark.png', 0);
INSERT INTO rebus_image_puzzle (image_word, word_lang, image_name, image_word_type) VALUES ('sheep', 1, 'sheep.png', 0);
INSERT INTO rebus_image_puzzle (image_word, word_lang, image_name, image_word_type) VALUES ('shell', 1, 'shell.png', 0);
INSERT INTO rebus_image_puzzle (image_word, word_lang, image_name, image_word_type) VALUES ('ship', 1, 'ship.png', 0);
INSERT INTO rebus_image_puzzle (image_word, word_lang, image_name, image_word_type) VALUES ('skull', 1, 'skull.png', 0);
INSERT INTO rebus_image_puzzle (image_word, word_lang, image_name, image_word_type) VALUES ('smile', 1, 'smile.png', 0);
INSERT INTO rebus_image_puzzle (image_word, word_lang, image_name, image_word_type) VALUES ('snake', 1, 'snake.png', 0);
INSERT INTO rebus_image_puzzle (image_word, word_lang, image_name, image_word_type) VALUES ('snow', 1, 'snow.png', 0);
INSERT INTO rebus_image_puzzle (image_word, word_lang, image_name, image_word_type) VALUES ('soap', 1, 'soap.png', 0);
INSERT INTO rebus_image_puzzle (image_word, word_lang, image_name, image_word_type) VALUES ('star', 1, 'star.png', 0);
INSERT INTO rebus_image_puzzle (image_word, word_lang, image_name, image_word_type) VALUES ('store', 1, 'store.png', 0);
INSERT INTO rebus_image_puzzle (image_word, word_lang, image_name, image_word_type) VALUES ('sun', 1, 'sun.png', 0);
INSERT INTO rebus_image_puzzle (image_word, word_lang, image_name, image_word_type) VALUES ('tooth', 1, 'tooth.png', 0);
INSERT INTO rebus_image_puzzle (image_word, word_lang, image_name, image_word_type) VALUES ('train', 1, 'train.png', 0);
INSERT INTO rebus_image_puzzle (image_word, word_lang, image_name, image_word_type) VALUES ('umbrella', 1, 'umbrella.png', 0);
INSERT INTO rebus_image_puzzle (image_word, word_lang, image_name, image_word_type) VALUES ('violin', 1, 'violin.png', 0);

INSERT INTO syllable (syllable) VALUES ('ax');
INSERT INTO syllable (syllable) VALUES ('xe');
INSERT INTO syllable (syllable) VALUES ('ba');
INSERT INTO syllable (syllable) VALUES ('ag');
INSERT INTO syllable (syllable) VALUES ('at');
INSERT INTO syllable (syllable) VALUES ('th');
INSERT INTO syllable (syllable) VALUES ('be');
INSERT INTO syllable (syllable) VALUES ('ed');
INSERT INTO syllable (syllable) VALUES ('ee');
INSERT INTO syllable (syllable) VALUES ('bi');
INSERT INTO syllable (syllable) VALUES ('ik');
INSERT INTO syllable (syllable) VALUES ('ke');
INSERT INTO syllable (syllable) VALUES ('no');
INSERT INTO syllable (syllable) VALUES ('ot');
INSERT INTO syllable (syllable) VALUES ('te');
INSERT INTO syllable (syllable) VALUES ('bo');
INSERT INTO syllable (syllable) VALUES ('on');
INSERT INTO syllable (syllable) VALUES ('ne');
INSERT INTO syllable (syllable) VALUES ('oo');
INSERT INTO syllable (syllable) VALUES ('tt');
INSERT INTO syllable (syllable) VALUES ('tl');
INSERT INTO syllable (syllable) VALUES ('le');
INSERT INTO syllable (syllable) VALUES ('bu');
INSERT INTO syllable (syllable) VALUES ('ug');
INSERT INTO syllable (syllable) VALUES ('us');
INSERT INTO syllable (syllable) VALUES ('ca');
INSERT INTO syllable (syllable) VALUES ('ak');
INSERT INTO syllable (syllable) VALUES ('an');
INSERT INTO syllable (syllable) VALUES ('nd');
INSERT INTO syllable (syllable) VALUES ('dl');
INSERT INTO syllable (syllable) VALUES ('ar');
INSERT INTO syllable (syllable) VALUES ('ch');
INSERT INTO syllable (syllable) VALUES ('he');
INSERT INTO syllable (syllable) VALUES ('es');
INSERT INTO syllable (syllable) VALUES ('se');
INSERT INTO syllable (syllable) VALUES ('co');
INSERT INTO syllable (syllable) VALUES ('om');
INSERT INTO syllable (syllable) VALUES ('mp');
INSERT INTO syllable (syllable) VALUES ('pu');
INSERT INTO syllable (syllable) VALUES ('ut');
INSERT INTO syllable (syllable) VALUES ('er');
INSERT INTO syllable (syllable) VALUES ('cr');
INSERT INTO syllable (syllable) VALUES ('ra');
INSERT INTO syllable (syllable) VALUES ('ab');
INSERT INTO syllable (syllable) VALUES ('cu');
INSERT INTO syllable (syllable) VALUES ('up');
INSERT INTO syllable (syllable) VALUES ('do');
INSERT INTO syllable (syllable) VALUES ('og');
INSERT INTO syllable (syllable) VALUES ('or');
INSERT INTO syllable (syllable) VALUES ('eg');
INSERT INTO syllable (syllable) VALUES ('gg');
INSERT INTO syllable (syllable) VALUES ('ey');
INSERT INTO syllable (syllable) VALUES ('ye');
INSERT INTO syllable (syllable) VALUES ('fi');
INSERT INTO syllable (syllable) VALUES ('ir');
INSERT INTO syllable (syllable) VALUES ('re');
INSERT INTO syllable (syllable) VALUES ('is');
INSERT INTO syllable (syllable) VALUES ('sh');
INSERT INTO syllable (syllable) VALUES ('fl');
INSERT INTO syllable (syllable) VALUES ('lo');
INSERT INTO syllable (syllable) VALUES ('ow');
INSERT INTO syllable (syllable) VALUES ('we');
INSERT INTO syllable (syllable) VALUES ('ha');
INSERT INTO syllable (syllable) VALUES ('ea');
INSERT INTO syllable (syllable) VALUES ('rt');
INSERT INTO syllable (syllable) VALUES ('ho');
INSERT INTO syllable (syllable) VALUES ('rs');
INSERT INTO syllable (syllable) VALUES ('li');
INSERT INTO syllable (syllable) VALUES ('io');
INSERT INTO syllable (syllable) VALUES ('ma');
INSERT INTO syllable (syllable) VALUES ('ap');
INSERT INTO syllable (syllable) VALUES ('mo');
INSERT INTO syllable (syllable) VALUES ('ou');
INSERT INTO syllable (syllable) VALUES ('od');
INSERT INTO syllable (syllable) VALUES ('ph');
INSERT INTO syllable (syllable) VALUES ('pi');
INSERT INTO syllable (syllable) VALUES ('ig');
INSERT INTO syllable (syllable) VALUES ('pl');
INSERT INTO syllable (syllable) VALUES ('la');
INSERT INTO syllable (syllable) VALUES ('ai');
INSERT INTO syllable (syllable) VALUES ('in');
INSERT INTO syllable (syllable) VALUES ('rk');
INSERT INTO syllable (syllable) VALUES ('ep');
INSERT INTO syllable (syllable) VALUES ('el');
INSERT INTO syllable (syllable) VALUES ('ll');
INSERT INTO syllable (syllable) VALUES ('hi');
INSERT INTO syllable (syllable) VALUES ('ip');
INSERT INTO syllable (syllable) VALUES ('sk');
INSERT INTO syllable (syllable) VALUES ('ku');
INSERT INTO syllable (syllable) VALUES ('ul');
INSERT INTO syllable (syllable) VALUES ('sm');
INSERT INTO syllable (syllable) VALUES ('mi');
INSERT INTO syllable (syllable) VALUES ('il');
INSERT INTO syllable (syllable) VALUES ('sn');
INSERT INTO syllable (syllable) VALUES ('na');
INSERT INTO syllable (syllable) VALUES ('so');
INSERT INTO syllable (syllable) VALUES ('oa');
INSERT INTO syllable (syllable) VALUES ('st');
INSERT INTO syllable (syllable) VALUES ('ta');
INSERT INTO syllable (syllable) VALUES ('to');
INSERT INTO syllable (syllable) VALUES ('su');
INSERT INTO syllable (syllable) VALUES ('un');
INSERT INTO syllable (syllable) VALUES ('tr');
INSERT INTO syllable (syllable) VALUES ('um');
INSERT INTO syllable (syllable) VALUES ('mb');
INSERT INTO syllable (syllable) VALUES ('br');
INSERT INTO syllable (syllable) VALUES ('vi');
INSERT INTO syllable (syllable) VALUES ('ol');

INSERT INTO word_syllable (syllable_id, rebus_image_puzzle_id) VALUES (1, 66);
INSERT INTO word_syllable (syllable_id, rebus_image_puzzle_id) VALUES (2, 66);
INSERT INTO word_syllable (syllable_id, rebus_image_puzzle_id) VALUES (3, 67);
INSERT INTO word_syllable (syllable_id, rebus_image_puzzle_id) VALUES (4, 67);
INSERT INTO word_syllable (syllable_id, rebus_image_puzzle_id) VALUES (3, 68);
INSERT INTO word_syllable (syllable_id, rebus_image_puzzle_id) VALUES (5, 68);
INSERT INTO word_syllable (syllable_id, rebus_image_puzzle_id) VALUES (3, 69);
INSERT INTO word_syllable (syllable_id, rebus_image_puzzle_id) VALUES (5, 69);
INSERT INTO word_syllable (syllable_id, rebus_image_puzzle_id) VALUES (6, 69);
INSERT INTO word_syllable (syllable_id, rebus_image_puzzle_id) VALUES (7, 70);
INSERT INTO word_syllable (syllable_id, rebus_image_puzzle_id) VALUES (8, 70);
INSERT INTO word_syllable (syllable_id, rebus_image_puzzle_id) VALUES (7, 71);
INSERT INTO word_syllable (syllable_id, rebus_image_puzzle_id) VALUES (9, 71);
INSERT INTO word_syllable (syllable_id, rebus_image_puzzle_id) VALUES (10, 72);
INSERT INTO word_syllable (syllable_id, rebus_image_puzzle_id) VALUES (11, 72);
INSERT INTO word_syllable (syllable_id, rebus_image_puzzle_id) VALUES (12, 72);
INSERT INTO word_syllable (syllable_id, rebus_image_puzzle_id) VALUES (13, 73);
INSERT INTO word_syllable (syllable_id, rebus_image_puzzle_id) VALUES (14, 73);
INSERT INTO word_syllable (syllable_id, rebus_image_puzzle_id) VALUES (15, 73);
INSERT INTO word_syllable (syllable_id, rebus_image_puzzle_id) VALUES (16, 74);
INSERT INTO word_syllable (syllable_id, rebus_image_puzzle_id) VALUES (17, 74);
INSERT INTO word_syllable (syllable_id, rebus_image_puzzle_id) VALUES (18, 74);
INSERT INTO word_syllable (syllable_id, rebus_image_puzzle_id) VALUES (16, 75);
INSERT INTO word_syllable (syllable_id, rebus_image_puzzle_id) VALUES (19, 75);
INSERT INTO word_syllable (syllable_id, rebus_image_puzzle_id) VALUES (14, 75);
INSERT INTO word_syllable (syllable_id, rebus_image_puzzle_id) VALUES (16, 76);
INSERT INTO word_syllable (syllable_id, rebus_image_puzzle_id) VALUES (14, 76);
INSERT INTO word_syllable (syllable_id, rebus_image_puzzle_id) VALUES (20, 76);
INSERT INTO word_syllable (syllable_id, rebus_image_puzzle_id) VALUES (21, 76);
INSERT INTO word_syllable (syllable_id, rebus_image_puzzle_id) VALUES (22, 76);
INSERT INTO word_syllable (syllable_id, rebus_image_puzzle_id) VALUES (23, 77);
INSERT INTO word_syllable (syllable_id, rebus_image_puzzle_id) VALUES (24, 77);
INSERT INTO word_syllable (syllable_id, rebus_image_puzzle_id) VALUES (23, 78);
INSERT INTO word_syllable (syllable_id, rebus_image_puzzle_id) VALUES (25, 78);
INSERT INTO word_syllable (syllable_id, rebus_image_puzzle_id) VALUES (26, 79);
INSERT INTO word_syllable (syllable_id, rebus_image_puzzle_id) VALUES (27, 79);
INSERT INTO word_syllable (syllable_id, rebus_image_puzzle_id) VALUES (12, 79);
INSERT INTO word_syllable (syllable_id, rebus_image_puzzle_id) VALUES (26, 80);
INSERT INTO word_syllable (syllable_id, rebus_image_puzzle_id) VALUES (28, 80);
INSERT INTO word_syllable (syllable_id, rebus_image_puzzle_id) VALUES (29, 80);
INSERT INTO word_syllable (syllable_id, rebus_image_puzzle_id) VALUES (30, 80);
INSERT INTO word_syllable (syllable_id, rebus_image_puzzle_id) VALUES (22, 80);
INSERT INTO word_syllable (syllable_id, rebus_image_puzzle_id) VALUES (26, 81);
INSERT INTO word_syllable (syllable_id, rebus_image_puzzle_id) VALUES (31, 81);
INSERT INTO word_syllable (syllable_id, rebus_image_puzzle_id) VALUES (26, 82);
INSERT INTO word_syllable (syllable_id, rebus_image_puzzle_id) VALUES (5, 82);
INSERT INTO word_syllable (syllable_id, rebus_image_puzzle_id) VALUES (32, 83);
INSERT INTO word_syllable (syllable_id, rebus_image_puzzle_id) VALUES (33, 83);
INSERT INTO word_syllable (syllable_id, rebus_image_puzzle_id) VALUES (9, 83);
INSERT INTO word_syllable (syllable_id, rebus_image_puzzle_id) VALUES (34, 83);
INSERT INTO word_syllable (syllable_id, rebus_image_puzzle_id) VALUES (35, 83);
INSERT INTO word_syllable (syllable_id, rebus_image_puzzle_id) VALUES (36, 84);
INSERT INTO word_syllable (syllable_id, rebus_image_puzzle_id) VALUES (37, 84);
INSERT INTO word_syllable (syllable_id, rebus_image_puzzle_id) VALUES (38, 84);
INSERT INTO word_syllable (syllable_id, rebus_image_puzzle_id) VALUES (39, 84);
INSERT INTO word_syllable (syllable_id, rebus_image_puzzle_id) VALUES (40, 84);
INSERT INTO word_syllable (syllable_id, rebus_image_puzzle_id) VALUES (15, 84);
INSERT INTO word_syllable (syllable_id, rebus_image_puzzle_id) VALUES (41, 84);
INSERT INTO word_syllable (syllable_id, rebus_image_puzzle_id) VALUES (42, 85);
INSERT INTO word_syllable (syllable_id, rebus_image_puzzle_id) VALUES (43, 85);
INSERT INTO word_syllable (syllable_id, rebus_image_puzzle_id) VALUES (44, 85);
INSERT INTO word_syllable (syllable_id, rebus_image_puzzle_id) VALUES (45, 86);
INSERT INTO word_syllable (syllable_id, rebus_image_puzzle_id) VALUES (46, 86);
INSERT INTO word_syllable (syllable_id, rebus_image_puzzle_id) VALUES (47, 87);
INSERT INTO word_syllable (syllable_id, rebus_image_puzzle_id) VALUES (48, 87);
INSERT INTO word_syllable (syllable_id, rebus_image_puzzle_id) VALUES (47, 88);
INSERT INTO word_syllable (syllable_id, rebus_image_puzzle_id) VALUES (19, 88);
INSERT INTO word_syllable (syllable_id, rebus_image_puzzle_id) VALUES (49, 88);
INSERT INTO word_syllable (syllable_id, rebus_image_puzzle_id) VALUES (50, 89);
INSERT INTO word_syllable (syllable_id, rebus_image_puzzle_id) VALUES (51, 89);
INSERT INTO word_syllable (syllable_id, rebus_image_puzzle_id) VALUES (52, 90);
INSERT INTO word_syllable (syllable_id, rebus_image_puzzle_id) VALUES (53, 90);
INSERT INTO word_syllable (syllable_id, rebus_image_puzzle_id) VALUES (54, 91);
INSERT INTO word_syllable (syllable_id, rebus_image_puzzle_id) VALUES (55, 91);
INSERT INTO word_syllable (syllable_id, rebus_image_puzzle_id) VALUES (56, 91);
INSERT INTO word_syllable (syllable_id, rebus_image_puzzle_id) VALUES (54, 92);
INSERT INTO word_syllable (syllable_id, rebus_image_puzzle_id) VALUES (57, 92);
INSERT INTO word_syllable (syllable_id, rebus_image_puzzle_id) VALUES (58, 92);
INSERT INTO word_syllable (syllable_id, rebus_image_puzzle_id) VALUES (59, 93);
INSERT INTO word_syllable (syllable_id, rebus_image_puzzle_id) VALUES (60, 93);
INSERT INTO word_syllable (syllable_id, rebus_image_puzzle_id) VALUES (61, 93);
INSERT INTO word_syllable (syllable_id, rebus_image_puzzle_id) VALUES (62, 93);
INSERT INTO word_syllable (syllable_id, rebus_image_puzzle_id) VALUES (41, 93);
INSERT INTO word_syllable (syllable_id, rebus_image_puzzle_id) VALUES (63, 94);
INSERT INTO word_syllable (syllable_id, rebus_image_puzzle_id) VALUES (5, 94);
INSERT INTO word_syllable (syllable_id, rebus_image_puzzle_id) VALUES (33, 95);
INSERT INTO word_syllable (syllable_id, rebus_image_puzzle_id) VALUES (64, 95);
INSERT INTO word_syllable (syllable_id, rebus_image_puzzle_id) VALUES (31, 95);
INSERT INTO word_syllable (syllable_id, rebus_image_puzzle_id) VALUES (65, 95);
INSERT INTO word_syllable (syllable_id, rebus_image_puzzle_id) VALUES (66, 96);
INSERT INTO word_syllable (syllable_id, rebus_image_puzzle_id) VALUES (49, 96);
INSERT INTO word_syllable (syllable_id, rebus_image_puzzle_id) VALUES (67, 96);
INSERT INTO word_syllable (syllable_id, rebus_image_puzzle_id) VALUES (35, 96);
INSERT INTO word_syllable (syllable_id, rebus_image_puzzle_id) VALUES (68, 97);
INSERT INTO word_syllable (syllable_id, rebus_image_puzzle_id) VALUES (69, 97);
INSERT INTO word_syllable (syllable_id, rebus_image_puzzle_id) VALUES (17, 97);
INSERT INTO word_syllable (syllable_id, rebus_image_puzzle_id) VALUES (70, 98);
INSERT INTO word_syllable (syllable_id, rebus_image_puzzle_id) VALUES (71, 98);
INSERT INTO word_syllable (syllable_id, rebus_image_puzzle_id) VALUES (72, 99);
INSERT INTO word_syllable (syllable_id, rebus_image_puzzle_id) VALUES (17, 99);
INSERT INTO word_syllable (syllable_id, rebus_image_puzzle_id) VALUES (18, 99);
INSERT INTO word_syllable (syllable_id, rebus_image_puzzle_id) VALUES (52, 99);
INSERT INTO word_syllable (syllable_id, rebus_image_puzzle_id) VALUES (72, 100);
INSERT INTO word_syllable (syllable_id, rebus_image_puzzle_id) VALUES (19, 100);
INSERT INTO word_syllable (syllable_id, rebus_image_puzzle_id) VALUES (17, 100);
INSERT INTO word_syllable (syllable_id, rebus_image_puzzle_id) VALUES (72, 101);
INSERT INTO word_syllable (syllable_id, rebus_image_puzzle_id) VALUES (73, 101);
INSERT INTO word_syllable (syllable_id, rebus_image_puzzle_id) VALUES (40, 101);
INSERT INTO word_syllable (syllable_id, rebus_image_puzzle_id) VALUES (6, 101);
INSERT INTO word_syllable (syllable_id, rebus_image_puzzle_id) VALUES (13, 102);
INSERT INTO word_syllable (syllable_id, rebus_image_puzzle_id) VALUES (19, 102);
INSERT INTO word_syllable (syllable_id, rebus_image_puzzle_id) VALUES (74, 102);
INSERT INTO word_syllable (syllable_id, rebus_image_puzzle_id) VALUES (30, 102);
INSERT INTO word_syllable (syllable_id, rebus_image_puzzle_id) VALUES (22, 102);
INSERT INTO word_syllable (syllable_id, rebus_image_puzzle_id) VALUES (34, 102);
INSERT INTO word_syllable (syllable_id, rebus_image_puzzle_id) VALUES (13, 103);
INSERT INTO word_syllable (syllable_id, rebus_image_puzzle_id) VALUES (14, 103);
INSERT INTO word_syllable (syllable_id, rebus_image_puzzle_id) VALUES (15, 103);
INSERT INTO word_syllable (syllable_id, rebus_image_puzzle_id) VALUES (75, 104);
INSERT INTO word_syllable (syllable_id, rebus_image_puzzle_id) VALUES (66, 104);
INSERT INTO word_syllable (syllable_id, rebus_image_puzzle_id) VALUES (17, 104);
INSERT INTO word_syllable (syllable_id, rebus_image_puzzle_id) VALUES (18, 104);
INSERT INTO word_syllable (syllable_id, rebus_image_puzzle_id) VALUES (76, 105);
INSERT INTO word_syllable (syllable_id, rebus_image_puzzle_id) VALUES (77, 105);
INSERT INTO word_syllable (syllable_id, rebus_image_puzzle_id) VALUES (78, 106);
INSERT INTO word_syllable (syllable_id, rebus_image_puzzle_id) VALUES (79, 106);
INSERT INTO word_syllable (syllable_id, rebus_image_puzzle_id) VALUES (28, 106);
INSERT INTO word_syllable (syllable_id, rebus_image_puzzle_id) VALUES (18, 106);
INSERT INTO word_syllable (syllable_id, rebus_image_puzzle_id) VALUES (43, 107);
INSERT INTO word_syllable (syllable_id, rebus_image_puzzle_id) VALUES (80, 107);
INSERT INTO word_syllable (syllable_id, rebus_image_puzzle_id) VALUES (81, 107);
INSERT INTO word_syllable (syllable_id, rebus_image_puzzle_id) VALUES (58, 108);
INSERT INTO word_syllable (syllable_id, rebus_image_puzzle_id) VALUES (63, 108);
INSERT INTO word_syllable (syllable_id, rebus_image_puzzle_id) VALUES (31, 108);
INSERT INTO word_syllable (syllable_id, rebus_image_puzzle_id) VALUES (82, 108);
INSERT INTO word_syllable (syllable_id, rebus_image_puzzle_id) VALUES (58, 109);
INSERT INTO word_syllable (syllable_id, rebus_image_puzzle_id) VALUES (33, 109);
INSERT INTO word_syllable (syllable_id, rebus_image_puzzle_id) VALUES (9, 109);
INSERT INTO word_syllable (syllable_id, rebus_image_puzzle_id) VALUES (83, 109);
INSERT INTO word_syllable (syllable_id, rebus_image_puzzle_id) VALUES (58, 110);
INSERT INTO word_syllable (syllable_id, rebus_image_puzzle_id) VALUES (33, 110);
INSERT INTO word_syllable (syllable_id, rebus_image_puzzle_id) VALUES (84, 110);
INSERT INTO word_syllable (syllable_id, rebus_image_puzzle_id) VALUES (85, 110);
INSERT INTO word_syllable (syllable_id, rebus_image_puzzle_id) VALUES (58, 111);
INSERT INTO word_syllable (syllable_id, rebus_image_puzzle_id) VALUES (86, 111);
INSERT INTO word_syllable (syllable_id, rebus_image_puzzle_id) VALUES (87, 111);
INSERT INTO word_syllable (syllable_id, rebus_image_puzzle_id) VALUES (88, 112);
INSERT INTO word_syllable (syllable_id, rebus_image_puzzle_id) VALUES (89, 112);
INSERT INTO word_syllable (syllable_id, rebus_image_puzzle_id) VALUES (90, 112);
INSERT INTO word_syllable (syllable_id, rebus_image_puzzle_id) VALUES (85, 112);
INSERT INTO word_syllable (syllable_id, rebus_image_puzzle_id) VALUES (91, 113);
INSERT INTO word_syllable (syllable_id, rebus_image_puzzle_id) VALUES (92, 113);
INSERT INTO word_syllable (syllable_id, rebus_image_puzzle_id) VALUES (93, 113);
INSERT INTO word_syllable (syllable_id, rebus_image_puzzle_id) VALUES (22, 113);
INSERT INTO word_syllable (syllable_id, rebus_image_puzzle_id) VALUES (94, 114);
INSERT INTO word_syllable (syllable_id, rebus_image_puzzle_id) VALUES (95, 114);
INSERT INTO word_syllable (syllable_id, rebus_image_puzzle_id) VALUES (27, 114);
INSERT INTO word_syllable (syllable_id, rebus_image_puzzle_id) VALUES (12, 114);
INSERT INTO word_syllable (syllable_id, rebus_image_puzzle_id) VALUES (94, 115);
INSERT INTO word_syllable (syllable_id, rebus_image_puzzle_id) VALUES (13, 115);
INSERT INTO word_syllable (syllable_id, rebus_image_puzzle_id) VALUES (61, 115);
INSERT INTO word_syllable (syllable_id, rebus_image_puzzle_id) VALUES (96, 116);
INSERT INTO word_syllable (syllable_id, rebus_image_puzzle_id) VALUES (97, 116);
INSERT INTO word_syllable (syllable_id, rebus_image_puzzle_id) VALUES (71, 116);
INSERT INTO word_syllable (syllable_id, rebus_image_puzzle_id) VALUES (98, 117);
INSERT INTO word_syllable (syllable_id, rebus_image_puzzle_id) VALUES (99, 117);
INSERT INTO word_syllable (syllable_id, rebus_image_puzzle_id) VALUES (31, 117);
INSERT INTO word_syllable (syllable_id, rebus_image_puzzle_id) VALUES (98, 118);
INSERT INTO word_syllable (syllable_id, rebus_image_puzzle_id) VALUES (100, 118);
INSERT INTO word_syllable (syllable_id, rebus_image_puzzle_id) VALUES (49, 118);
INSERT INTO word_syllable (syllable_id, rebus_image_puzzle_id) VALUES (56, 118);
INSERT INTO word_syllable (syllable_id, rebus_image_puzzle_id) VALUES (101, 119);
INSERT INTO word_syllable (syllable_id, rebus_image_puzzle_id) VALUES (102, 119);
INSERT INTO word_syllable (syllable_id, rebus_image_puzzle_id) VALUES (100, 120);
INSERT INTO word_syllable (syllable_id, rebus_image_puzzle_id) VALUES (19, 120);
INSERT INTO word_syllable (syllable_id, rebus_image_puzzle_id) VALUES (14, 120);
INSERT INTO word_syllable (syllable_id, rebus_image_puzzle_id) VALUES (6, 120);
INSERT INTO word_syllable (syllable_id, rebus_image_puzzle_id) VALUES (103, 121);
INSERT INTO word_syllable (syllable_id, rebus_image_puzzle_id) VALUES (43, 121);
INSERT INTO word_syllable (syllable_id, rebus_image_puzzle_id) VALUES (80, 121);
INSERT INTO word_syllable (syllable_id, rebus_image_puzzle_id) VALUES (81, 121);
INSERT INTO word_syllable (syllable_id, rebus_image_puzzle_id) VALUES (104, 122);
INSERT INTO word_syllable (syllable_id, rebus_image_puzzle_id) VALUES (105, 122);
INSERT INTO word_syllable (syllable_id, rebus_image_puzzle_id) VALUES (106, 122);
INSERT INTO word_syllable (syllable_id, rebus_image_puzzle_id) VALUES (56, 122);
INSERT INTO word_syllable (syllable_id, rebus_image_puzzle_id) VALUES (84, 122);
INSERT INTO word_syllable (syllable_id, rebus_image_puzzle_id) VALUES (85, 122);
INSERT INTO word_syllable (syllable_id, rebus_image_puzzle_id) VALUES (79, 122);
INSERT INTO word_syllable (syllable_id, rebus_image_puzzle_id) VALUES (107, 123);
INSERT INTO word_syllable (syllable_id, rebus_image_puzzle_id) VALUES (69, 123);
INSERT INTO word_syllable (syllable_id, rebus_image_puzzle_id) VALUES (108, 123);
INSERT INTO word_syllable (syllable_id, rebus_image_puzzle_id) VALUES (68, 123);
INSERT INTO word_syllable (syllable_id, rebus_image_puzzle_id) VALUES (81, 123);

CREATE INDEX wordind ON rebus_image_puzzle (image_word);